apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "charts-common-deployment.name" . }}
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "charts-common-deployment.labels" . | nindent 4 }}
spec:
  {{- if not .Values.global.autoscaling.enabled }}
  replicas: {{ .Values.global.deployment.replicaCount }}
  {{- end }}
  progressDeadlineSeconds: {{ .Values.global.deployment.failSeconds }}
  revisionHistoryLimit: {{ .Values.global.deployment.revisionHistory }}
  strategy:
    {{- toYaml .Values.global.deployment.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "charts-common-deployment.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.global.deployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "charts-common-deployment.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.deployment.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "charts-common-deployment.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.global.security.podSecurityContext | nindent 8 }}
      {{- if or .Values.global.configMap.enabled .Values.global.pvc.enabled (and (eq .Values.global.destination "gcp") .Values.global.secrets.enabled) }}
      volumes:
        {{- if .Values.global.configMap.enabled }}
        - name: app-config
          configMap:
            name: {{ .Values.global.configMap.name }}
            items:
              - key: {{ .Values.global.configMap.fileName }}
                path: {{ .Values.global.configMap.fileName }}
            defaultMode: 420
        {{- end }}
        {{- if .Values.global.pvc.enabled }}
        - name: storage
          persistentVolumeClaim:
            claimName: {{ include "charts-common-deployment.name" . }}-pvc
        {{- end }}
        {{- if and (eq .Values.global.destination "gcp") .Values.global.secrets.enabled }}
        - name: gcpsecrets
          csi:
            driver: secrets-store-gke.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "charts-common-deployment.name" . }}
        {{- end }}
      {{- end }}

      containers:
        - name: {{ include "charts-common-deployment.name" . }}
          image: "{{ .Values.global.deployment.image.uri }}"
          imagePullPolicy: {{ .Values.global.deployment.image.pullPolicy }}
          {{- if .Values.global.deployment.image.command }}
          command: {{- toYaml .Values.global.deployment.image.command | nindent 12 }}
          {{- end }}
          {{- if .Values.global.deployment.image.args }}
          args: {{- toYaml .Values.global.deployment.image.args | nindent 12 }}
          {{- end }}
          {{- if .Values.global.service.enabled }}
          ports:
            {{- range $key, $val := .Values.global.service.ports }}
            - name: {{ $key }}
              containerPort: {{ $val.inner }}
              protocol: TCP
            {{- end }}
          {{- end }}
          {{- if or .Values.global.configMap.enabled .Values.global.pvc.enabled (and (eq .Values.global.destination "gcp") .Values.global.secrets.enabled) }}
          volumeMounts:
            {{- if .Values.global.configMap.enabled }}
            - name: app-config
              readOnly: true
              mountPath: {{ .Values.global.configMap.mountPath }}
              subPath: {{ .Values.global.configMap.fileName }}
            {{- end }}
            {{- if .Values.global.pvc.enabled }}
            - name: storage
              mountPath: {{ .Values.global.pvc.mountPath }}
              subPath: {{ .Values.global.pvc.subPath }}
              readOnly: false
            {{- end }}
            {{- if and (eq .Values.global.destination "gcp") .Values.global.secrets.enabled }}
            {{- range .Values.global.secrets.data }}
            - name: gcpsecrets
              mountPath: {{ $.Values.global.secrets.mountPath }}/{{ .fileName }}
              subPath: {{ .fileName }}
              readOnly: true
            {{- end }}
            {{- end }}
          {{- end }}
          
          {{- if .Values.global.deployment.readiness }}
          readinessProbe:
            {{- toYaml .Values.global.deployment.readiness | nindent 12 }}
          {{- end }}
          {{- if .Values.global.deployment.liveness }}
          livenessProbe:
            {{- toYaml .Values.global.deployment.liveness | nindent 12 }}
          {{- end }}
          env:
            {{- toYaml .Values.global.deployment.env | nindent 12 }}
          resources:
            {{- toYaml .Values.global.deployment.resources | nindent 12 }}
          {{- if .Values.global.deployment.lifecycle }}
          lifecycle:
            {{- toYaml .Values.global.deployment.lifecycle | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.global.security.securityContext | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      {{- with .Values.global.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: {{ .Values.global.deployment.deregistrationTime }}
      {{- with .Values.global.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.deployment.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
          labelSelector:
            matchLabels:
              {{- include "charts-common-deployment.selectorLabels" $ | nindent 14 }}
      {{- end }}