apiVersion: v2
name: charts-statefulset
description: Umbrella chart for Magicorn StatefulSet workloads
type: application
version: 1.1.1
appVersion: "0.0.1"

dependencies:
- name: charts-common
  version: "0.0.1"
  repository: "file://../common"
- name: charts-common-statefulset
  version: "0.0.1"
  repository: "file://../common-statefulset"