apiVersion: v2
name: charts-statefulset
description: Umbrella chart for Magicorn StatefulSet workloads
type: application
version: 1.2.0
appVersion: "0.0.1"

dependencies:
- name: charts-common
  version: "1.0.0"
  repository: "file://../common"
