{{- if eq .Values.destination "datacenter" }}
{{- $root := . }}
{{- $ingressLength := len .Values.ingress }}
{{- range $index, $ingress := .Values.ingress }}
{{- if $ingress.enabled -}}
{{- if and $ingress.className (not (semverCompare ">=1.18-0" $root.Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey $ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set $ingress.annotations "kubernetes.io/ingress.class" $ingress.className}}
  {{- end }}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "charts-deployment.name" $root }}{{ if gt $ingressLength 1 }}-{{ add1 $index }}{{ end }}
  namespace: "{{ $root.Release.Namespace }}"
  labels:
    {{- include "charts-deployment.labels" $root | nindent 4 }}
  annotations:
    {{- toYaml $ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ $ingress.className }}
  rules:
    {{- range $ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "charts-deployment.name" $root }}
                port:
                  number: {{ $root.Values.service.ports.one.outer }}
              {{- else }}
              serviceName: {{ include "charts-deployment.name" $root }}
              servicePort: {{ $root.Values.service.ports.one.outer }}
              {{- end }}
          {{- end }}
    {{- end }}
---
{{- end }}
{{- end }}
{{- end }}