{{- if .Values.prehooks.otherPrehooks.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "charts-deployment.fullname" . }}-prehooks
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "charts-deployment.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      {{- with .Values.deployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "charts-deployment.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.deployment.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "charts-deployment.serviceAccountName" . }}
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.deployment.image.uri }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          {{- if .Values.prehooks.otherPrehooks.command }}
          command: {{- toYaml .Values.prehooks.otherPrehooks.command | nindent 12 }}
          {{- end }}
          {{- if .Values.prehooks.otherPrehooks.args }}
          args: {{- toYaml .Values.prehooks.otherPrehooks.args | nindent 12 }}
          {{- end }}
          env:
            {{- toYaml .Values.deployment.env | nindent 12 }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
{{- end }}