{{- if .Values.rollout.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "charts-deployment.name" . }}
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "charts-deployment.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.deployment.replicaCount }}
  {{- end }}
  progressDeadlineSeconds: {{ .Values.deployment.failSeconds }}
  revisionHistoryLimit: {{ .Values.rollout.revisionHistory }}
  selector:
    matchLabels:
      {{- include "charts-deployment.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.deployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "charts-deployment.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.deployment.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "charts-deployment.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.security.podSecurityContext | nindent 8 }}
      {{- if or .Values.configMap.enabled .Values.pvc.enabled (and (eq .Values.destination "gcp") .Values.secrets.enabled) }}
      volumes:
        {{- if .Values.configMap.enabled }}
        - name: app-config
          configMap:
            name: {{ .Values.configMap.name }}
            items:
              - key: {{ .Values.configMap.fileName }}
                path: {{ .Values.configMap.fileName }}
            defaultMode: 420
        {{- end }}
        {{- if .Values.pvc.enabled }}
        - name: storage
          persistentVolumeClaim:
            claimName: {{ include "charts-deployment.name" . }}-pvc
        {{- end }}
        {{- if and (eq .Values.destination "gcp") .Values.secrets.enabled }}
        - name: gcpsecrets
          csi:
            driver: secrets-store-gke.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "charts-deployment.name" . }}
        {{- end }}
      {{- end }}

      containers:
        - name: {{ include "charts-deployment.name" . }}
          image: "{{ .Values.deployment.image.uri }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          {{- if .Values.deployment.image.command }}
          command: {{- toYaml .Values.deployment.image.command | nindent 12 }}
          {{- end }}
          {{- if .Values.deployment.image.args }}
          args: {{- toYaml .Values.deployment.image.args | nindent 12 }}
          {{- end }}
          {{- if .Values.service.enabled }}
          ports:
            {{- range $key, $val := .Values.service.ports }}
            - name: {{ $key }}
              containerPort: {{ $val.inner }}
              protocol: TCP
            {{- end }}
          {{- end }}
          {{- if or .Values.configMap.enabled .Values.pvc.enabled (and (eq .Values.destination "gcp") .Values.secrets.enabled) }}
          volumeMounts:
            {{- if .Values.configMap.enabled }}
            - name: app-config
              readOnly: true
              mountPath: {{ .Values.configMap.mountPath }}
              subPath: {{ .Values.configMap.fileName }}
            {{- end }}
            {{- if .Values.pvc.enabled }}
            - name: storage
              mountPath: {{ .Values.pvc.mountPath }}
              subPath: {{ .Values.pvc.subPath }}
              readOnly: false
            {{- end }}
            {{- if and (eq .Values.destination "gcp") .Values.secrets.enabled }}
            {{- range .Values.secrets.data }}
            - name: gcpsecrets
              mountPath: {{ $.Values.secrets.mountPath }}/{{ .fileName }}
              subPath: {{ .fileName }}
              readOnly: true
            {{- end }}
            {{- end }}
          {{- end }}
          
          {{- if .Values.deployment.readiness }}
          readinessProbe:
            {{- toYaml .Values.deployment.readiness | nindent 12 }}
          {{- end }}
          {{- if .Values.deployment.liveness }}
          livenessProbe:
            {{- toYaml .Values.deployment.liveness | nindent 12 }}
          {{- end }}
          env:
            {{- toYaml .Values.deployment.env | nindent 12 }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
          {{- if .Values.deployment.lifecycle }}
          lifecycle:
            {{- toYaml .Values.deployment.lifecycle | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.security.securityContext | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: {{ .Values.deployment.deregistrationTime }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
          labelSelector:
            matchLabels:
              {{- include "charts-deployment.selectorLabels" $ | nindent 14 }}
      {{- end }}
  strategy:
    {{- if eq .Values.rollout.strategyType "canary" }}
    canary:
      {{- if .Values.rollout.canary.createCanaryService }}
      stableService: {{ .Values.rollout.canary.stableServiceName | default (printf "%s-stable" (include "charts-deployment.name" .)) }}
      canaryService: {{ .Values.rollout.canary.canaryServiceName | default (printf "%s-canary" (include "charts-deployment.name" .)) }}
      {{- end }}
      {{- if .Values.rollout.canary.maxSurge }}
      maxSurge: {{ .Values.rollout.canary.maxSurge }}
      {{- end }}
      {{- if .Values.rollout.canary.maxUnavailable }}
      maxUnavailable: {{ .Values.rollout.canary.maxUnavailable }}
      {{- end }}
      {{- if .Values.rollout.canary.steps }}
      steps:
        {{- toYaml .Values.rollout.canary.steps | nindent 8 }}
      {{- end }}
      {{- if .Values.rollout.canary.trafficRouting.enabled }}
      trafficRouting:
        {{- if eq .Values.rollout.canary.trafficRouting.type "alb" }}
        alb:
          ingress: {{ include "charts-deployment.name" . }}
          servicePort: {{ (index .Values.service.ports "one").outer }}
        {{- else if eq .Values.rollout.canary.trafficRouting.type "istio" }}
        istio:
          virtualService:
            name: {{ include "charts-deployment.name" . }}
        {{- else if eq .Values.rollout.canary.trafficRouting.type "nginx" }}
        nginx:
          stableIngress: {{ include "charts-deployment.name" . }}
        {{- end }}
      {{- end }}
      {{- if .Values.rollout.canary.analysis.enabled }}
      analysis:
        templates:
        - templateName: {{ .Values.rollout.canary.analysis.templateName }}
        {{- if .Values.rollout.canary.analysis.args }}
        args:
          {{- toYaml .Values.rollout.canary.analysis.args | nindent 10 }}
        {{- end }}
      {{- end }}
    {{- else if eq .Values.rollout.strategyType "blueGreen" }}
    blueGreen:
      activeService: {{ .Values.rollout.blueGreen.activeService | default (printf "%s-active" (include "charts-deployment.name" .)) }}
      {{- if or .Values.rollout.blueGreen.previewService (not .Values.rollout.blueGreen.previewService) }}
      previewService: {{ .Values.rollout.blueGreen.previewService | default (printf "%s-preview" (include "charts-deployment.name" .)) }}
      {{- end }}
      autoPromotionEnabled: {{ .Values.rollout.blueGreen.autoPromotionEnabled }}
      {{- if .Values.rollout.blueGreen.autoPromotionSeconds }}
      autoPromotionSeconds: {{ .Values.rollout.blueGreen.autoPromotionSeconds }}
      {{- end }}
      {{- if .Values.rollout.blueGreen.scaleDownDelaySeconds }}
      scaleDownDelaySeconds: {{ .Values.rollout.blueGreen.scaleDownDelaySeconds }}
      {{- end }}
      {{- if .Values.rollout.blueGreen.previewReplicaCount }}
      previewReplicaCount: {{ .Values.rollout.blueGreen.previewReplicaCount }}
      {{- end }}
      {{- if .Values.rollout.blueGreen.analysis.enabled }}
      prePromotionAnalysis:
        templates:
        - templateName: {{ .Values.rollout.blueGreen.analysis.templateName }}
        {{- if .Values.rollout.blueGreen.analysis.args }}
        args:
          {{- toYaml .Values.rollout.blueGreen.analysis.args | nindent 10 }}
        {{- end }}
      {{- end }}
    {{- end }}
{{- end }}

