{{- if .Values.security.sgPolicy.enabled }}
apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: {{ .Values.name }}
  namespace: "{{ .Release.Namespace }}"
spec:
  serviceAccountSelector: 
    matchLabels: 
      app: {{ .Values.name }}
  securityGroups:
    groupIds: 
      - {{ .Values.security.sgPolicy.securityGroupId }}
{{- end }}
