{{- if .Values.security.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "charts-deployment.serviceAccountName" . }}
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "charts-deployment.labels" . | nindent 4 }}
  {{- $annotations := dict }}
  {{- if .Values.security.serviceAccount.annotations }}
  {{- range $key, $value := .Values.security.serviceAccount.annotations }}
  {{- $_ := set $annotations $key $value }}
  {{- end }}
  {{- end }}
  {{- if and (eq .Values.destination "gke") .Values.security.serviceAccount.gcpServiceAccount }}
  {{- $_ := set $annotations "iam.gke.io/gcp-service-account" .Values.security.serviceAccount.gcpServiceAccount }}
  {{- end }}
  {{- if gt (len $annotations) 0 }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
{{- end }}
