{{- if eq .Values.destination "datacenter" }}
{{- if .Values.service.enabled }}
{{- $skipMainService := false }}
{{- if .Values.rollout.enabled }}
  {{- if or (eq .Values.rollout.strategyType "blueGreen") .Values.rollout.canary.createCanaryService }}
    {{- $skipMainService = true }}
  {{- end }}
{{- end }}
{{- if not $skipMainService }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "charts-deployment.name" . }}
  namespace: "{{ .Release.Namespace }}"
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  labels:
    {{- include "charts-deployment.labels" . | nindent 4 }}
spec:
  {{- if eq .Values.service.type "None" }}
  type: ClusterIP
  clusterIP: None
  {{- else }}
  type: {{ .Values.service.type }}
  {{- end }}
  ports:
    {{- range $key, $val := .Values.service.ports }}
    - name: {{ $key }}
      targetPort: {{ $val.inner }}
      port: {{ $val.outer }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "charts-deployment.selectorLabels" . | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
