{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "charts-deployment.fullname" . }}
  labels:
    {{- include "charts-deployment.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "charts-deployment.selectorLabels" . | nindent 4 }}
{{- end }}
