{{- if .Values.global.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "charts-common.name" . }}
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "charts-common.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "charts-common.name" . }}
  minReplicas: {{ .Values.global.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.global.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.global.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.global.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.global.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.global.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  {{- if .Values.global.autoscaling.behavior }}
  behavior:
    {{- toYaml .Values.global.autoscaling.behavior | nindent 4 }}
  {{- end }}
{{- end }}
