{{- if .Values.prehooks.otherPrehooks.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "charts-common.name" . }}-prehooks
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "charts-common.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      {{- with .Values.deployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "charts-common.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.deployment.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "charts-common.serviceAccountName" . }}
      restartPolicy: Never
      {{- if or .Values.configMap.enabled (and (eq .Values.destination "gcp") .Values.secrets.enabled) }}
      volumes:
        {{- if .Values.configMap.enabled }}
        - name: app-config
          configMap:
            name: {{ .Values.configMap.name }}
            items:
              - key: {{ .Values.configMap.fileName }}
                path: {{ .Values.configMap.fileName }}
            defaultMode: 420
        {{- end }}
        {{- if and (eq .Values.destination "gcp") .Values.secrets.enabled }}
        - name: gcpsecrets
          csi:
            driver: secrets-store-gke.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "charts-common.name" . }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.deployment.image.uri }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          {{- if .Values.prehooks.otherPrehooks.command }}
          command: {{- toYaml .Values.prehooks.otherPrehooks.command | nindent 12 }}
          {{- end }}
          {{- if .Values.prehooks.otherPrehooks.args }}
          args: {{- toYaml .Values.prehooks.otherPrehooks.args | nindent 12 }}
          {{- end }}
          {{- if or .Values.configMap.enabled (and (eq .Values.destination "gcp") .Values.secrets.enabled) }}
          volumeMounts:
            {{- if .Values.configMap.enabled }}
            - name: app-config
              readOnly: true
              mountPath: {{ .Values.configMap.mountPath }}
              subPath: {{ .Values.configMap.fileName }}
            {{- end }}
            {{- if and (eq .Values.destination "gcp") .Values.secrets.enabled }}
            {{- range .Values.secrets.data }}
            - name: gcpsecrets
              mountPath: {{ $.Values.secrets.mountPath }}/{{ .fileName }}
              subPath: {{ .fileName }}
              readOnly: true
            {{- end }}
            {{- end }}
          {{- end }}
          env:
            {{- toYaml .Values.deployment.env | nindent 12 }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
{{- end }}