{{- if eq .Values.global.destination "aws" }}
{{- if .Values.global.security.sgPolicy.enabled }}
apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: {{ include "charts-common.name" . }}
  namespace: "{{ .Release.Namespace }}"
spec:
  serviceAccountSelector: 
    matchLabels: 
      {{- include "charts-common.selectorLabels" . | nindent 6 }}
  securityGroups:
    groupIds: 
      - {{ .Values.global.security.sgPolicy.securityGroupId }}
{{- end }}
{{- end }}
